name: college-tennis
services:
  - name: api
    git:
      branch: main
      repo_clone_url: https://github.com/juanmarino15/collegetennisanalytics.git
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: /
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      
  - name: collector
    git:
      branch: main
      repo_clone_url: https://github.com/juanmarino15/collegetennisanalytics.git
    dockerfile_path: Dockerfile
    command: python collector/update_data.py --all
    instance_count: 1
    instance_size_slug: basic-xs
    source_dir: /
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}

databases:
  - engine: PG
    name: college-tennis-db
    version: "14"
    size: db-s-dev-database